// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tD154sPM9uw90h1iwd0wexOUp6jqgk4',
    appId: '1:478939925379:web:8821301e0a334b6b2ac4b6',
    messagingSenderId: '478939925379',
    projectId: 'chat-app-6a8de',
    authDomain: 'chat-app-6a8de.firebaseapp.com',
    storageBucket: 'chat-app-6a8de.firebasestorage.app',
    measurementId: 'G-EM0N0SV32T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjTQjY0fzLhVOIjTAModPSi2I0GLBYlI',
    appId: '1:478939925379:android:2cc62335720d418b2ac4b6',
    messagingSenderId: '478939925379',
    projectId: 'chat-app-6a8de',
    storageBucket: 'chat-app-6a8de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxpdLubCgOSrU7NW4Hn_0PVNjULlFmgI',
    appId: '1:478939925379:ios:c55fe2b5663cfa892ac4b6',
    messagingSenderId: '478939925379',
    projectId: 'chat-app-6a8de',
    storageBucket: 'chat-app-6a8de.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxpdLubCgOSrU7NW4Hn_0PVNjULlFmgI',
    appId: '1:478939925379:ios:c55fe2b5663cfa892ac4b6',
    messagingSenderId: '478939925379',
    projectId: 'chat-app-6a8de',
    storageBucket: 'chat-app-6a8de.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6tD154sPM9uw90h1iwd0wexOUp6jqgk4',
    appId: '1:478939925379:web:8c3a5415257d745a2ac4b6',
    messagingSenderId: '478939925379',
    projectId: 'chat-app-6a8de',
    authDomain: 'chat-app-6a8de.firebaseapp.com',
    storageBucket: 'chat-app-6a8de.firebasestorage.app',
    measurementId: 'G-ZLVYM7V59W',
  );
}
